### ISSUE TITLE
SDL 1.2.15 won't compile on OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#54]
Originally reported by: **Robert McGovern (Bitbucket: [tarasis](http://bitbucket.org/tarasis), GitHub: [tarasis](http://github.com/tarasis))**

----------------------------------------

Was just trying to compile the project for myself, unfortunately the SDL library that is required will not compile on Mavericks because CGDirectPaletteRef has been removed.

Build output:

./src/video/quartz/SDL_QuartzVideo.h:94:5: error: unknown type name 'CGDirectPaletteRef'
    CGDirectPaletteRef palette;            /* palette of an 8-bit display */
    ^
./src/video/quartz/SDL_QuartzEvents.m:816:13: warning: 'UpdateSystemActivity' is deprecated: first deprecated in OS X 10.8
      [-Wdeprecated-declarations]
            UpdateSystemActivity(UsrActivity);
            ^
/Applications/Xcode5-DP.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/Power.h:367:1: note: 
      'UpdateSystemActivity' declared here
UpdateSystemActivity(UInt8 activity)                          __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0,__MAC_10_8,__IPHONE_NA,__IPHONE_NA);
^
1 warning and 1 error generated.

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/54

**Comment by derSteFfi** [comment]
I read this as resolved?

**Comment by lynxlynxlynx** [comment]
We're now using SDL2 anyway, so closing.
