### PR TITLE
Externalizing Town and Town Sectors data

### PR DESCRIPTION
**Pull request by ja2-derek**
Externalization of Town and Town Sector data, in a similar manner as #1018. 

See #665 and #1011.

## Summary

- Externalizing basic town info. See assets/externalized/strategic-map-towns.json for the schema
- Adding TownModel class, which can be retrieved by `townId`
- Replacing the hard-coded tables of `InitializeStrategicMapSectorTownNames`, `sBaseSectorList`, `pTownPoints` and `MilitiaTrainingAllowedInTown`

##  What's not included

* Town names - they are defined in translation string files
* Is Town hidden - codebase has very specific logic for Tixa and Orta. It will require a lot of code change to generalize the logic
* Base sector - it is now calculated at init time

This PR conflicts with #1018. I will re-base when it is merged to master.

### CODE REVIEW

File: src/externalized/strategic/TownModel.cc [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+	}
+
+	Assert( obj.HasMember("townPoint") && obj["townPoint"].IsObject() );
+	auto tp = obj["townPoint"].GetObject();
+	SGPPoint townPoint = SGPPoint();
+	townPoint.iX = tp["x"].GetInt();
+	townPoint.iY = tp["y"].GetInt();
+
+	JsonObjectReader reader(obj);
+;	return new TownModel(
```
Comment (lynxlynxlynx) [inline src/externalized/strategic/TownModel.cc:35]: There's an extraneous semicolon here.

**Comment by lynxlynxlynx** [comment]
`TownModel.cc:25:63: error: ‘SECTOR_FROM_COORDINATES’ was not declared in this scope`

**Comment by lynxlynxlynx** [comment]
LGTM.

Should also the names be externalized? I don't know if WF left them the same, but now there's just the choice of the existing ones.

**Comment by ja2-derek** [comment]
I am not sure. I can put the English towns names in the JSON, but we will lose the localizations like this:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/8e2396f0021f97b36cd89ba2d894725ecb796e38/src/game/Utils/_RussianText.cc#L217-L231

Or should we externalize the whole translation file instead? What do you think?

**Comment by ja2-derek** [comment]
Town names in Wildfire.

image

**Comment by lynxlynxlynx** [comment]
How to make shit sound Spanish 101. ;) So for WF, either some extra code is needed, with San Mona as the outlier, or the names replaced in all languages.

In the longterm the whole translations as non-code sounds better, but let's not get distracted. I suggest we add an array to the cities json to hold the original and all the translated versions. Then your WF mod can still achieve its thing by simply overriding it with its own file. 

Is the id used also for something else? I guess since there's a 1:1 map, it doesn't really matter.

**Comment by ja2-derek** [comment]
I personally prefer vanilla town names lol

**Comment by lynxlynxlynx** [comment]
The point is that any new data projects can then have any names they like, it's not just for WF. But we can leave it be for now.

**Comment by flaviojs** [comment]
It's better to implement only what is needed since using json implies coding a lot logic.

I would wait for a true scripting language (lua? js?) to be integrated before thinking of what future mods need.

**Comment by lynxlynxlynx** [comment]
It's not just about the future though, but also eg. Unfinished Business. We haven't reviewed and merged all the code changes yet #254 , but the more is externalized, the fewer conflicts need to end up as ifdefs etc.

**Comment by ja2-derek** [comment]
While we are at town names... do you know Russian or Polish? What does "locative" mean and how important is it?

It only seems make a difference in RUS and PL.

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/8e2396f0021f97b36cd89ba2d894725ecb796e38/src/game/Utils/_RussianText.cc#L234-L249

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/8e2396f0021f97b36cd89ba2d894725ecb796e38/src/game/Utils/_PolishText.cc#L234-L249

**Comment by lynxlynxlynx** [comment]
It's from declination. Without it, nouns can look completely wrong in a sentence. I think it's present in all Slavic languages, no Romanic and don't know about the rest.

**Comment by ja2-derek** [comment]
I think I will not put those inside the TownModel, but rather put that under externalized/strings, and handle with `ContentManager::loadStringRes`, just like ammo calibres.

**Comment by lynxlynxlynx** [comment]
That works too, but is harder to use. Considering the low activity of the community, I don't think it matters that much.

**Comment by ja2-derek** [comment]
Yes, it would be less straight-forward to mod creators, but more convenient too translators.

**Comment by lynxlynxlynx** [comment]
This one is now complete, right — I can merge?

**Comment by ja2-derek** [comment]
Yes please!

**Comment by lynxlynxlynx** [comment]
Thanks!
