### ISSUE TITLE
Cannot compile with GCC 15.1.1

### ISSUE THREAD

**Issue by selaux** [ja2-stracciatella/ja2-stracciatella#2168]
I currently cannot compile the source code, as there is some issue with compiling with GCC 15.1.1.

```
-- The C compiler identification is GNU 15.1.1
-- The CXX compiler identification is GNU 15.1.1
```

The error itself seems to originate from our usage of `sol2`

```
In file included from /XXX/ja2-stracciatella/src/externalized/scripting/ScriptingExtensionsLua.cc:7:
/XXX/ja2-stracciatella/_bin/lib-sol2/src/single/include/sol/sol.hpp: In member function ‘T& sol::optional<T&>::emplace(Args&& ...)’:
/XXX/ja2-stracciatella/_bin/lib-sol2/src/single/include/sol/sol.hpp:6059:31: error: ‘class sol::optional<T&>’ has no member named ‘construct’ [-Wtemplate-body]
 6059 |                         this->construct(std::forward<Args>(args)...);
      |                               ^~~~~~~~~
make[2]: *** [CMakeFiles/ja2.dir/build.make:317: CMakeFiles/ja2.dir/src/externalized/scripting/ScriptingExtensionsLua.cc.o] Error 1
```

Seems like CLang 19.1 has the same issue: https://github.com/ThePhD/sol2/issues/1617

@misanthropos I've seen that you applied some patches to the Gentoo sol2 version which fix those issues. Do you know which combination of patches is needed to make it work? Then we could apply them to our version of `sol2` as well.

**Comment by selaux** [comment]
I think I merged too soon. The patch fails to apply for me:

```
/bin/sh: -c: line 2: syntax error: unexpected end of file
make[2]: *** [CMakeFiles/get-sol2.dir/build.make:118: get-sol2-prefix/src/get-sol2-stamp/get-sol2-patch] Error 2
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/get-sol2.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by lynxlynxlynx** [comment]
Hmm, that's odd, failed parsing in both.
