### ISSUE TITLE
Fails to build with miniaudio-0.11.9

### ISSUE THREAD

**Issue by yurivict** [ja2-stracciatella/ja2-stracciatella#1567]
### What is wrong

Fails to build with miniaudio-0.11.9

```
/wrkdirs/usr/ports/games/jaggedalliance2/work/ja2-stracciatella-0.19.1/src/sgp/SoundMan.cc:493:17: error: no matching function for call to 'ma_decoder_read_pcm_frames'
                        framesRead = ma_decoder_read_pcm_frames(sample->pDecoder, pFramesInClientFormat, bytesToWrite);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/miniaudio/miniaudio.h:62234:18: note: candidate function not viable: requires 4 arguments, but 3 were provided
MA_API ma_result ma_decoder_read_pcm_frames(ma_decoder* pDecoder, void* pFramesOut, ma_uint64 frameCount, ma_uint64* pFramesRead)
                 ^
/wrkdirs/usr/ports/games/jaggedalliance2/work/ja2-stracciatella-0.19.1/src/sgp/SoundMan.cc:496:22: error: no matching function for call to 'ma_data_converter_get_required_input_frame_count'
                        auto posInBytes = ma_data_converter_get_required_input_frame_count(sample->pDataConverter, channel->Pos) * bytesPerFrame;
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/miniaudio/miniaudio.h:52727:18: note: candidate function not viable: requires 3 arguments, but 2 were provided
MA_API ma_result ma_data_converter_get_required_input_frame_count(const ma_data_converter* pConverter, ma_uint64 outputFrameCount, ma_uint64* pInputFrameCount)
                 ^
/wrkdirs/usr/ports/games/jaggedalliance2/work/ja2-stracciatella-0.19.1/src/sgp/SoundMan.cc:497:35: error: no matching function for call to 'ma_data_converter_get_required_input_frame_count'
                        auto requiredInputFrameCount = ma_data_converter_get_required_input_frame_count(sample->pDataConverter, bytesToWrite);
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/miniaudio/miniaudio.h:52727:18: note: candidate function not viable: requires 3 arguments, but 2 were provided
MA_API ma_result ma_data_converter_get_required_input_frame_count(const ma_data_converter* pConverter, ma_uint64 outputFrameCount, ma_uint64* pInputFrameCount)
                 ^
/wrkdirs/usr/ports/games/jaggedalliance2/work/ja2-stracciatella-0.19.1/src/sgp/SoundMan.cc:516:12: error: no matching function for call to 'ma_pcm_rb_commit_write'
                result = ma_pcm_rb_commit_write(channel->pRingBuffer, framesRead, pFramesInClientFormat);
                         ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/miniaudio/miniaudio.h:54295:18: note: candidate function not viable: requires 2 arguments, but 3 were provided
MA_API ma_result ma_pcm_rb_commit_write(ma_pcm_rb* pRB, ma_uint32 sizeInFrames)
                 ^
```

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19.1 | n/a |    yes    |    no     |

**Comment by lynxlynxlynx** [comment]
We don't support that release; it clearly broke some APIs. So best not to use the system one.

**Comment by selaux** [comment]
We could use [static_assert](https://en.cppreference.com/w/cpp/language/static_assert) to enforce the minor version on `MA_VERSION_MINOR`. Also upgrading miniaudio to `0.11.x` does not seem to be that hard on first glance, so we might take a shot at this...

Second option would be to have some conditions around `MA_VERSION_MINOR` to support both versions at one, but I'd rather not do that for a header only library.

**Comment by selaux** [comment]
@yurivict Could you try with the `miniaudio-version-cmake-tests` branch from this repo? It should work with miniaudio 0.11.x

**Comment by yurivict** [comment]
@lynxlynxlynx ja2-stracciatella-0.19.1 fails to build with miniaudio-0.11.11:

```
/wrkdirs/usr/ports/games/jaggedalliance2/work/ja2-stracciatella-0.19.1/src/sgp/SoundMan.cc:493:17: error: no matching function for call to 'ma_decoder_read_pcm_frames'
                        framesRead = ma_decoder_read_pcm_frames(sample->pDecoder, pFramesInClientFormat, bytesToWrite);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/miniaudio/miniaudio.h:62901:18: note: candidate function not viable: requires 4 arguments, but 3 were provided
MA_API ma_result ma_decoder_read_pcm_frames(ma_decoder* pDecoder, void* pFramesOut, ma_uint64 frameCount, ma_uint64* pFramesRead)
                 ^
/wrkdirs/usr/ports/games/jaggedalliance2/work/ja2-stracciatella-0.19.1/src/sgp/SoundMan.cc:496:22: error: no matching function for call to 'ma_data_converter_get_required_input_frame_count'
                        auto posInBytes = ma_data_converter_get_required_input_frame_count(sample->pDataConverter, channel->Pos) * bytesPerFrame;
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by lynxlynxlynx** [comment]
Yes, this was fixed for 0.20, there won't be any more releases in the 0.19 branch. Give us a few more days and it'll be out.
